"""=Add 'user_roles' constraints

Revision ID: 035b9fd75f39
Revises: ce637ff6e131
Create Date: 2024-05-30 19:15:53.268879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035b9fd75f39'
down_revision = 'ce637ff6e131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint('user_roles_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('user_roles_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint('user_roles_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('user_roles_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key('user_roles_ibfk_1', 'roles', ['role_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key('user_roles_ibfk_2', 'users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###
